### ISSUE TITLE
Better documentation needed in the README.md file

### ISSUE THREAD

**Issue by hjmjohnson** [InsightSoftwareConsortium/ITKPerformanceVisualization#6]
What is the intent of this code base?  How should one use it?

The README.md is so sparse that it is impossible to know how this code is to be used.

Can an example usage be created?

**Comment by jakestrauss** [comment]
This repo is for a visualization tool for the performance benchmark test data. It is in development and won’t be ready for use for a couple of months. The pull request to master today was by mistake...we will update the README with proper description and usage instructions before it is completed.

**Comment by hjmjohnson** [comment]
@jakestrauss Has there been any progress on this project?  Will there be documentation?

**Comment by jakestrauss** [comment]
Yes, the initial phase of the project, which was completed as an undergraduate computer science capstone class at UNC-Chapel Hill, is complete. The ReadMe has been updated with appropriate usage instructions.

**Comment by hjmjohnson** [comment]
There are only 4 systems represented here:

![image](https://user-images.githubusercontent.com/313970/56981481-97c92200-6b44-11e9-9c8e-c9c888015404.png)


I personally have submitted MUCH more data than this.  Why are other nodes not present?

**Comment by hjmjohnson** [comment]
https://data.kitware.com/#collection/57b5c9e58d777f126827f5a1/folder/5af50c818d777f06857985e3

 In particular I'm interested in `argon-lc-h21-32.hpc`

**Comment by jakestrauss** [comment]
Our current implementation only loads data from a selected subset of folders, as there is too much data to download it all to the client side. This is obviously not ideal, and we suggest that it be remedied by hosting the data on a SQL database that can be queried as needed (outlined in our design document here: https://docs.google.com/document/d/1KefTJq8YKsru8QNANrKbZxv_by-7HXmj5sYq4w7BOr0/edit?usp=sharing). Unfortunately the semester has come to a close for us and our involvement with this project is over, so such a change would need to come from the ITK dev community.

**Comment by fbudin69500** [comment]
@jakestrauss Thanks for this nice contribution. It will be very helpful to understand how to improve ITK. Also, you are part of the ITK community, so feel free to contribute more patches in the future if you find time for it :)
